sonaric-network/kits

avail/avail.yaml
ethereum.yaml
gnosis.yaml
polygon.yaml
solana.yaml

added requirements for avail, ethereum and solana

[feature] added templates requirements

---

avail/avail.yaml
mina/mina.yaml

avail: added runnable for turing network

avail: added runnable for turing network

---

ritual/MANIFEST
ritual/README.md
ritual/files/config.json
ritual/files/fluent-bit.conf
ritual/files/redis.conf
ritual/ritual.yaml

added ritual template
related: https://monk-io.atlassian.net/browse/CORE-2030

[chore] added ritual template: CORE-2030

---

eigen-layer/MANIFEST
eigen-layer/README.md
eigen-layer/eigen-layer.yaml
eigen-layer/files/config.end

added MANIFEST, template, README and config
related: https://monk-io.atlassian.net/browse/CORE-2027

[feature] added MANIFEST, template, README and config: CORE-2027

---

avail/avail.yaml
avail/files/light/config.toml
docs/avail.md

[chore] changed the 7000 port to 7001

---

MANIFEST
README.md
celestia/MANIFEST
celestia/celestia.yaml
docs/celestia.md

added celestia light client templates with docs usage examples and get token action
provided templates for main netbeta, arabica and mocha

added celestia light client templates

---

celestia/celestia.yaml

Celestia storage and bridge templates

Celestia storage and bridge templates

---

celestia/celestia.yaml

celestia added icon

---

avail/MANIFEST
avail/avail.yaml
avail/files/scripts/rotate-keys.sh
avail/files/scripts/validator-entrypoint.sh

avail: fixed turing validator; chore, upgrade and separation of all validator chain types
integrated restart node script in actions

avail: validator fixes, restart node logic in actions

---

avail/avail.yaml
celestia/celestia.yaml
docs/avail.md
eigen-layer/eigen-layer.yaml
mina/mina.yaml
solana.yaml

avail: updated docs, added more examples, requirements, all node types examples, troubleshooting, Avail docs references, table of contents, mentioning rpc API with links to docs
avail: added health action (need it to check if node is synced)
template and docs: chores, better naming
avail: minor fixes in ports, updated avail image tag to v.1.11.0.0

avail docs update, added check sync action

---

avail/avail.yaml
celestia/celestia.yaml
eigen-layer/eigen-layer.yaml
ethereum.yaml
gnosis.yaml
mina/mina.yaml
polygon.yaml
solana.yaml

Added icons and version details for YAML templates
- Updated avail.yaml: Added version details
- Updated celestia.yaml: Added version details
- Updated eigen-layer.yaml: Added version details
- Updated ethereum.yaml: Added icon and version details
- Updated gnosis.yaml: Added icon and version details
- Updated mina.yaml: Added icon and version details
- Updated polygon.yaml: Added icon and version details
- Updated solana.yaml: Added version details

[chore] added icons and versions for templates

---

avail/avail.yaml
celestia/celestia.yaml
eigen-layer/eigen-layer.yaml
ethereum/ethereum.yaml
gnosis.yaml
mina/mina.yaml
polygon.yaml
ritual/ritual.yaml
solana.yaml

Added currency parameter to all templates specifying the currency.
related: https://monk-io.atlassian.net/browse/CORE-2121

[chore] added currency for all templates: CORE-2121

---

docs/mina.md
mina/mina.yaml

updated get-balance and get-address actions to print json
updated doc
added lock/unlock account actions which might be useful

Mina updated actions to get balance and address to return json, lock/unlock accounts actions

---

mina/mina.yaml

mina: fixed get-address: removed argument

mina: fixed get-address: removed argument

---

mina/mina.yaml

get-balance, get-address actions:
handle cases when daemon hasn't started yet

mina: json actions: added error handling

---

solana.yaml

added import-key and export-key wallet
related: https://monk-io.atlassian.net/browse/CORE-2058

[chore] added import-key and export-key wallet: CORE-2058

---

avail/avail.yaml
celestia/MANIFEST
celestia/celestia.yaml
celestia/files/export.sh
celestia/files/import.sh
celestia/files/start.sh
ethereum/ethereum.yaml
gnosis.yaml
mina/mina.yaml
polygon.yaml
solana.yaml

updated disk requirements and changed it to GB everywhere
celestia: refactor, separated scripts in files 
added `wallet-support` field in metadata which lists wallet-related actions, e.g. `import-key, export-key, list-keys`
grammar fixes

[chore] updated requirements, added wallet-support metadata, grammar fixes

---

avail/avail.yaml

added latest images supporting mainnet for Avail

added mainnet runnables for Avail

---

zkagi.yaml

zkagi base template

---

zkagi.yaml

zkagi template: added nodeIP and ports, changed image

zkagi template: added nodeIP and ports, changed image

---

MANIFEST
docs/livepeer.md
livepeer/MANIFEST
livepeer/files/start.sh
livepeer/livepeer.yaml

added a livepeer template and added a wallet and doc

[chore] added a livepeer template and added a wallet and doc: CORE-2053

---

solana.yaml

added json output for get-balance and get-address
related: https://monk-io.atlassian.net/browse/CORE-2058

[chore] added json output for get-balance and get-address: CORE-2058

---

aleo/MANIFEST
aleo/aleo.yaml
aleo/files/entrypoint.sh
aleo/files/import-key.sh
aleo/files/start.sh
docs/aleo.md

aleo template: added import, export and doc

aleo template: added import, export and doc

---

docs/eigen-layer.md
eigen-layer/Dockerfile
eigen-layer/MANIFEST
eigen-layer/eigen.yaml
eigen-layer/files/scripts/import-key.sh
eigen-layer/files/scripts/op-create-config.sh
eigen-layer/files/scripts/op-register.sh

eigenlayer: added operator actions and documentation

eigenlayer: added operator actions and documentation

---

docs/livepeer.md
livepeer/files/start.sh
livepeer/livepeer.yaml

small fix start.sh for livepeer

[chore] small fix start.sh for livepeer

---

docs/koii.md
koii/MANIFEST
koii/files/config.env
koii/files/keygen.sh
koii/files/start.sh
koii/koii.yaml

[chore] added a koii template and doc: CORE-2166

---

celestia/celestia.yaml
celestia/files/start.sh
docs/celestia.md

- opened rpc port 26658
- updated base image version to v.0.16.0
- fixes in startup script
- get address
- get balance
- updated doc

celestia: opened rpc port 26658, fixed startup script, upgraded base image version

---

rollkit.yaml

basic rollkit template

---

rollkit.yaml

rollkit: added celestia integration example

rollkit: added celestia integration example

---

rollkit.yaml

Celestia rollkit: fixed frontend and added base actions for gm

Celestia rollkit: fixed frontend and added base actions for gm

---

rollkit.yaml

rollkit: removed duplicate ports to have an ability to run group on single node

rollkit: removed duplicate ports

---

berachain/MANIFEST
berachain/berachain.yaml
berachain/files/entrypoint.sh

[chore] added template berachain :CORE-2181

---

beacon-kit.yaml
docs/beacon-kit.md

added template rollkit and documentation

[chore] added template rollkit : CORE-2181

---

README.md
docs/ethereum.md
ethereum/ethereum.yaml

thorax/erigon can't be found
temporarily removed sync status action, since curl is not part of this image

ethereum: switched to erigontech/erigon:v2.60.10 image
